<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="12846" started-at="2018-05-12T07:09:18Z" finished-at="2018-05-12T07:09:31Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="12846" started-at="2018-05-12T07:09:18Z" finished-at="2018-05-12T07:09:31Z">
      <class name="testcase.CaseLoginTest">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:testcase.CaseLoginTest@627551fb]" name="beforeClass" is-config="true" duration-ms="11" started-at="2018-05-12T15:09:18Z" finished-at="2018-05-12T15:09:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="loginTest()[pri:0, instance:testcase.CaseLoginTest@627551fb]" name="loginTest" duration-ms="12813" started-at="2018-05-12T15:09:18Z" finished-at="2018-05-12T15:09:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<退出> but was:<出>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<退出> but was:<出>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at testcase.CaseLoginTest.loginTest(CaseLoginTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="signOutTest()[pri:0, instance:testcase.CaseLoginTest@627551fb]" name="signOutTest" duration-ms="2" started-at="2018-05-12T15:09:31Z" finished-at="2018-05-12T15:09:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signOutTest -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:testcase.CaseLoginTest@627551fb]" name="afterClass" is-config="true" duration-ms="0" started-at="2018-05-12T15:09:31Z" finished-at="2018-05-12T15:09:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- testcase.CaseLoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
